vim.keymap.set({"n"}, "<F4>", "<cmd>CMake select_target<CR>", {buffer = true})
vim.keymap.set({"n"}, "<F5>", "<cmd>CMake build_and_run<CR>", {buffer = true})
vim.keymap.set({"n"}, "<F29>", "<cmd>CMake build_and_debug<CR>", {buffer = true})
vim.keymap.set({"n"}, "<F6>", "<cmd>CMake run<CR>", {buffer = true})
vim.keymap.set({"n"}, "<F30>", "<cmd>CMake debug<CR>", {buffer = true})
vim.keymap.set({"n"}, "<C-B>", "<cmd>CMake build<CR>", {buffer = true})
