vim.keymap.set({ "n" }, "<C-_>", "<cmd>noh<CR>", { desc = "Stop highlighting search pattern" })

vim.keymap.set({ "n" }, "<Tab>", "<cmd>bn<CR>", { desc = "Switch to next buffer" })
vim.keymap.set({ "n" }, "<S-Tab>", "<cmd>bp<CR>", { desc = "Switch to previous buffer" })

vim.keymap.set({ "n" }, "<C-k>", "<C-w>k", { desc = "Move cursor to window below current one" })
vim.keymap.set({ "n" }, "<C-j>", "<C-w>j", { desc = "Move cursor to window above current one" })
vim.keymap.set({ "n" }, "<C-h>", "<C-w>h", { desc = "Move cursor to window left of current one" })
vim.keymap.set({ "n" }, "<C-l>", "<C-w>l", { desc = "Move cursor to window right of current one" })

vim.keymap.set({ "n" }, "<leader>bf", vim.lsp.buf.format, { desc = "Run lsp format command on current buffer" })
vim.keymap.set({ "n" }, "gD", vim.lsp.buf.declaration, { desc = "Go to symbol declaration" })
vim.keymap.set({ "n" }, "gd", vim.lsp.buf.definition, { desc = "Go to symbol definition" })
vim.keymap.set({ "n" }, "K", vim.lsp.buf.hover, { desc = "Show hover window" })
vim.keymap.set({ "n" }, "gi", vim.lsp.buf.implementation, { desc = "Go to implementation" })
-- vim.keymap.set({ "n" }, "<C-k>", vim.lsp.buf.signature_help, {desc = "Show signature help"})
vim.keymap.set({ "n" }, "<leader>rn", vim.lsp.buf.rename, { desc = "Rename symbol under cursor" })
vim.keymap.set({ "n" }, "gr", vim.lsp.buf.references, { desc = "Find references to symbol" })
vim.keymap.set({ "n" }, "<leader>ca", vim.lsp.buf.code_action, { desc = "Show available code actions" })
vim.keymap.set({ "n" }, "gl", vim.diagnostic.open_float, { desc = "Open diagnositcs floating window" })
vim.keymap.set({ "n" }, "[d", vim.diagnostic.goto_prev, { desc = "Go to previous diagnostic" })
vim.keymap.set({ "n" }, "]d", vim.diagnostic.goto_next, { desc = "Go to next diagnostic" })
vim.keymap.set({ "n" }, "<leader>q", vim.diagnostic.setloclist, { desc = "" })
vim.cmd([[ command! Format execute 'lua vim.lsp.buf.formatting([{asyng=true}])' ]])
